services:
  bot:
    build: .
    container_name: tg_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - tgbot_data:/data
    ports:
      - "8080:8080"

volumes:
  tgbot_data:
